import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'apt1': 'Shasy',
          'apt2': 'Mitra',
          'apptitle': 'ShasyMitra',
          'welcome': 'Hi !! Welcome',
          'next': 'NEXT',
          'enter_otp': 'Enter OTP',
          'Login': 'LOGIN',
          'not_recieved_otp': 'Not Recieved OTP?',
          'resend': 'Resend',
          'help': 'Support',
          'complete_your_profile': 'COMPLETE YOUR PROFILE',
          'complete_now': 'Complete Now',
          'explore_services': 'Explore Services',
          'tracktor_book': 'Tractor Booking',
          'tubebell_book': 'Tubewell Booking',
          'Sell_crop': 'Sell Crop',
          'crop_doctor': 'Crop Doctor',
          'crop_calender': 'Crop Calendar',
          'crop_advisory': 'Crop Advisory',
          'hello': 'Hello_',
          'total_advance': 'Total Advance',
          'total_due': 'Total Amount',
          'serch_customer': 'Search Customer',
          'add_customer': 'Add Customer',
          'farmer_Name': 'Farmer Name',
          'farmer_no': 'Farmer Number',
          'crop_plans': 'Crop Plans',
          'home': 'Home',
          'completeprofilealert':
              'Please Complerte the Profile 80% to start this feature',
          'clouds': 'Clouds',
          'humidity': 'Humidity',
          'rainfall': 'Rainfall',
          'loacation': 'Location',
          'nxt5days': 'View next 5 days',
          'farm_Information': 'Farm Information',
          'edit_string': 'Edit',
          'log_out': 'Log Out',
          'your_farm_lands': 'Your Farm Land',
          'address': 'Address',
          'state': 'State',
          'district': 'District',
          'tehsile': 'Tehsile',
          'gramsabha': 'Gram Sabha',
          'pincode': 'Pincode',
          'account_holder_name': 'Account Holder Name',
          'land_number': 'Land Number ( Khata or Khasra Number )',
          'land_size': 'Land Size in Bigha or Acres, etc',
          'your_name': 'Your Name',
          'thana': 'Thana',
          'profile_information': 'Profile Information',
          'profile_complete': 'Get full access complete 100% profile',
          'view_all': 'View All',
          'Add_customer_bill': 'ग्राहक बिल जोड़ें',
          'save': 'Submit',
          'advance': 'Advance',
          'description': 'Description',
          'rate': 'Rate',
          'start_date ': 'Start Date',
          'enter_unit': 'Enter Unit',
          'ur_crop': 'Your crop',
          'selectcrop': 'Select crop',
          'prv_task': 'prv task',
          'next_task': 'next task',
          'Click_on_the_crop_to_show_your_task':
              'Click on the crop to show your task',
          'View_Task': 'View Task',
          'Choose_season': 'Please Choose Season',
          'Please_select_Season_First': 'Please select Season First',
          'Package_of_Practices': 'Package of Practices',
          'Crop_Protection': 'Crop Protection',
          'Current_Task': 'Current Task',
          'net_balance': 'Net Balance',
          'fill_customer_detail': 'Fill Customer Details',
          'add_cus_num_srch': 'Add From Contact',
          'Please_Search_or_Add_Customer': 'Please Search or Add Customer',
          'continue': 'Continue',
          'add_new_entry': 'Add New Entry',
          'Add_Irriagation': 'Add Irriagation',
          'start_time': 'Start Time',
          'end_time': 'End Time',
          'date': 'Date',
          'total': 'Total',
          'machinery': 'Machinery',
          'start_date': 'Start Date',
          'choose_your_product': 'Choose your product',
          'choose_your_crop': 'Choose Your Crop',
          'choose_your_disease': 'Choose Disease Name (Optional)',
          'your_selected_crop': 'Your Selected Crop',
          'variety_of_crop': 'Variety of Crop',
          'unit': 'Unit',
          'quantity_to_sell': 'Quantity to Sell',
          'upload_product_image': 'Upload Product Image',
          'click_here': 'Click Here',
          'pls_enter_expected_price': 'Please Enter Expected Price',
          'create_request': 'Submit',
          'Request_Submitted_Successfully': 'Request Submitted Successfully',
          'Paid': 'Paid',
          'Update_Payment': 'Update Payment',
          'Update': 'Update',
          'Payment_is_Empty': 'Payment is Empty.',
          'Bill_Updated_Successfully': 'Bill Updated Successfully',
          'Make_Full_Payment': 'Make Full Payment',
          'Payment_Due': 'Payment Due',
          'Payment_Collected': 'Payment Collected',
          'Full_Payment_Collected': 'Full Payment Collected.',
          'Partial_Payment_Collected': 'Partial Payment Collected.',
          'Name': 'Name',
          'Update_Payment_Status': 'Update Payment Status',
          'Curent_Due_Rs': 'Curent Due: Rs.',
          'Total_Amount_Rs': 'Total  Amount: Rs.',
          'Area_Type': 'Area Type',
          'Area_Size': 'Area Size',
          'Start_date': 'Date',
          'Machine': 'Machine',
          'Type': 'Type',
          'Tractor': 'Tractor',
          'Created_On': 'Created-On:',
          'Share': 'Share',
          'No_Data_Found': 'No Data Found',
          'click_crop': 'Click here show your crop plan task',
          'view_disease': 'View Disease',
          'edit_profile': 'Edit Profile',
          'add_farm_land': 'Add Farm Lands',
          'Title_Address': 'Title/Address',
          'Crop_health': 'Crop Health',
          'Instructions': 'Instructions',
          'ins1': 'Keep you camera close to the crop',
          'ins2': 'Ensure enough list is present',
          'ins3': 'Ensure photo is not blurred',
          'ins4': 'Clean camera lens before',
          'ins5': 'Keep the camera steady',
        },
        'hi_IN': {
          'apt1': 'शस्य',
          'apt2': 'मित्र:',
          'apptitle': 'शस्य मित्रः',
          'welcome': 'आपका स्वागत है',
          'next': 'आगे',
          'enter_otp': 'OTP दर्ज करें',
          'Login': 'लॉग इन करें',
          'not_recieved_otp': 'ओटीपी प्राप्त नहीं हुआ?',
          'resend': 'पुन: भेजें',
          'help': 'हेल्प',
          'complete_your_profile': 'अपनी प्रोफाइल पूरा करें',
          'complete_now': 'पूरा करें',
          'explore_services': 'हमारी सेवाएँ',
          'tracktor_book': 'ट्रैक्टर बुक',
          'tubebell_book': 'ट्यूबवेल बुक',
          'Sell_crop': 'फसल बिकरी',
          'crop_doctor': 'फसल डॉक्टर',
          'crop_calender': 'फसल कैलेंडर',
          'crop_advisory': 'फसल सुझाव',
          'hello': 'नमस्ते',
          'total_advance': 'कुल अग्रिम',
          'total_due': 'कुल रकम',
          'serch_customer': 'ग्राहक खोजें',
          'add_customer': 'ग्राहक जोड़ें',
          'farmer_Name': 'किसान का नाम',
          'farmer_no': 'फ़ोन नंबर',
          'crop_plans': 'फसल योजनाएँ',
          'home': 'होम ',
          'completeprofilealert':
              'इस सुविधा को शुरू करने के लिए कृपया प्रोफ़ाइल को 80% पूरा करें',
          'clouds': 'बादल',
          'humidity': 'नमी',
          'rainfall': 'वर्षा',
          'loacation': 'जगह',
          'nxt5days': 'अगले 5 दिन देखें',
          'farm_Information': 'खेत की जानकारी',
          'edit_string': 'संपादन',
          'log_out': 'लॉग आउट',
          'your_farm_lands': 'आपके खेत',
          'address': 'पता',
          'state': 'राज्य',
          'district': 'ज़िला',
          'tehsile': 'तहसील',
          'gramsabha': 'ग्राम सभा',
          'pincode': 'पिन कोड',
          'account_holder_name': 'खाताधारक का नाम',
          'land_number': 'भूमि संख्या (खाता या खसरा संख्या)',
          'land_size': 'बीघा या एकड़ आदि में भूमि का आकार',
          'your_name': 'आपका नाम',
          'thana': 'थाना',
          'profile_information': 'प्रोफाइल की जानकारी',
          'profile_complete': 'अपनी प्रोफ़ाइल 100% पूरी करें',
          'view_all': 'पुरा देखे',
          'Add_customer_bill': 'ग्राहक बिल जोड़ें',
          'save': 'सबमिट करें',
          'advance': 'एडवांस',
          'description': 'विवरण',
          'rate': 'रेट',
          'start_date ': 'आरंभ करने की तिथि',
          'enter_unit': 'इकाई दर्ज करें',
          'ur_crop': 'आपकी फसल',
          'selectcrop': 'फसल चयन',
          'prv_task': 'पिछला कार्य',
          'next_task': 'अगला कार्य',
          'Click_on_the_crop_to_show_your_task':
              ' अपना कार्य दिखाने के लिए फसल पर क्लिक करें',
          'View_Task': 'कार्य देखें',
          'Choose_season': 'कृपया सीज़न चुनें',
          'Please_select_Season_First': 'कृपया सीजन पहले चुनें',
          'Package_of_Practices': 'फसल सुझाव',
          'Crop_Protection': 'फसल सुरक्षा',
          'Current_Task': 'तत्कालीन काम',
          'net_balance': 'निवल शेष',
          'fill_customer_detail': 'ग्राहक विवरण भरें',
          'add_cus_num_srch': 'नंबर जोड़ें',
          'Please_Search_or_Add_Customer': 'कृपया खोजें या ग्राहक जोड़ें',
          'continue': 'जारी रखें',
          'add_new_entry': 'नई प्रविष्टि जोड़ें',
          'Add_Irriagation': 'सिंचाई जोड़ें',
          'start_time': 'समय शुरू',
          'end_time': 'अंतिम समय',
          'date': 'तारीख',
          'total': 'कुल',
          'machinery': 'मशीनरी',
          'Start_date': 'आरंभ करने की तिथि',
          'choose_your_product': 'अपना उत्पाद चुनें',
          'choose_your_crop': 'अपनी फसल चुनें',
          'choose_your_disease': 'रोग का नाम चुनें (वैकल्पिक)',
          'your_selected_crop': 'आपकी चयनित फसल',
          'variety_of_crop': 'फसल की किस्म',
          'unit': 'यूनिट',
          'quantity_to_sell': 'बेचने की मात्रा',
          'upload_product_image': 'उत्पाद छवि अपलोड करें',
          'click_here': 'यहाँ क्लिक करें',
          'pls_enter_expected_price': 'कृपया अपेक्षित मूल्य दर्ज करें',
          'create_request': 'दर्ज करें',
          'Request_Submitted_Successfully': 'अनुरोध सफलतापूर्वक सबमिट किया गया',
          'Paid': 'चुकाया गया',
          'Update_Payment': 'भुगतान अद्यतन करें',
          'Update': 'अपडेट करना',
          'Payment_is_Empty': 'भुगतान खाली है',
          'Bill_Updated_Successfully': 'बिल अपडेट सफलतापूर्वक',
          'Make_Full_Payment': 'पूरा भुगतान करें',
          'Payment_Due': 'भुगतान राशि',
          'Payment_Collected': 'भुगतान एकत्र किया गया',
          'Full_Payment_Collected': 'पूर्ण भुगतान एकत्र किया गया।',
          'Partial_Payment_Collected': 'आंशिक भुगतान एकत्र किया गया।',
          'Name': 'नाम',
          'Update_Payment_Status': 'अद्यतन भुगतान स्थिति',
          'Curent_Due_Rs': 'वर्तमान देय: रुपये।',
          'Total_Amount_Rs': 'कुल राशि: रुपये।',
          'Area_Type': 'क्षेत्र का प्रकार',
          'Area_Size': 'क्षेत्र का आकार',
          'Machine': 'मशीन',
          'Type': 'टाइप',
          'Tractor': 'ट्रैक्टर',
          'Created_On': 'पर बनाया:',
          'Share': 'शेयर करना',
          'No_Data_Found': 'कोई डेटा नहीं मिला',
          'click_crop': 'अपना फसल प्लान देखने के  लिए फसल पे क्लिक करें',
          'view_disease': 'फसल रोग देखें',
          'edit_profile': 'प्रोफ़ाइल संपादित करें',
          'add_farm_land': 'कृषि भूमि जोड़ें',
          'Title_Address': 'शीर्षक/पता',
          'Crop_health': 'फसल स्वास्थ्य',
          'Instructions': 'निर्देश',
          'ins1': 'कैमरे को फसल के करीब रखें',
          'ins2': 'सुनिश्चित करें कि पर्याप्त सूची मौजूद है',
          'ins3': 'सुनिश्चित करें कि फोटो धुंधली नहीं है',
          'ins4': 'कैमरे के लेंस को पहले साफ करें',
          'ins5': 'कैमरा स्थिर रखें',
        },
      };
}
